spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mongodb:
    embedded:
      version: 5.0.5
logging:
  level:
    root=DEBUG: